#!/bin/bash

if [ "$SNAP_ARCH" == "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" == "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" == "arm64" ]; then
  ARCH="aarch64-linux-gnu"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

PERL5LIB="$PERL5LIB:$SNAP/etc/perl"
PERL5LIB="$PERL5LIB:$SNAP/usr/local/lib/$ARCH/perl/5.22.1"
PERL5LIB="$PERL5LIB:$SNAP/usr/local/share/perl/5.22.1"
PERL5LIB="$PERL5LIB:$SNAP/usr/lib/$ARCH/perl5/5.22"
PERL5LIB="$PERL5LIB:$SNAP/usr/share/perl5"
PERL5LIB="$PERL5LIB:$SNAP/usr/lib/$ARCH/perl/5.22"
PERL5LIB="$PERL5LIB:$SNAP/usr/share/perl/5.22"
PERL5LIB="$PERL5LIB:$SNAP/usr/local/lib/site_perl"
PERL5LIB="$PERL5LIB:$SNAP/usr/lib/$ARCH/perl-base"
export PERL5LIB

export WGETRC="$SNAP/etc/wgetrc"

exec rmadison "$@"
