name: ubuntu-watch-packages
version: '0.4.6'
base: core18
summary: Helpful utility to watch specified packages in the ubuntu archive.
description: |
  Watch specified binary packages in the
  ubuntu archive for transition between archive pockets. Useful when waiting
  for a package update to be published.

  It polls the launchpad API for new packages every 10 minutes (you can
  change this by using poll-seconds option)

  Usage:

  ubuntu-watch-packages --help # to see all available options

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  ubuntu-watch-packages:
    environment:
      PATH: "$SNAP/usr/bin:$SNAP/bin/:$PATH"
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
    command: bin/snapcraft-preload $SNAP/bin/ubuntu-watch-packages
    plugs:
      - network
      - desktop
      - home

parts:
  ubuntu-watch-packages:
    plugin: python
    requirements:
     - src/requirements.txt
    source: .
    stage-packages:
      - libnotify-bin

  snapcraft-preload:
    source: https://github.com/diddledan/snapcraft-preload.git
    source-branch: semaphore-support
    plugin: cmake
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
