name: ubuntu-watch-packages
version: '0.1'
summary: Helpful utility to watch specified packages in the ubuntu archive.
description: |
  Watch specified packages, using rmadison in the ubuntu archive for transition
  between archive pockets. Useful when waiting for a package update to be
  published.

  It polls for new packages every 10 minutes (you can change this by using
  poll-seconds option)
grade: stable
confinement: strict

apps:
  ubuntu-watch-packages:
    command: wrapper
    plugs:
      - network
      - desktop

parts:
  ubuntu-watch-packages-wrapper:
    plugin: dump
    source: snap
    prepare: |
      chmod +x wrapper
    stage:
      - usr/bin/wrapper
      - usr/bin/rmadison-wrapper
    organize:
      wrapper: usr/bin/wrapper
      rmadison-wrapperwrapper: usr/bin/rmadison-wrapper

  ubuntu-watch-packages:
    plugin: python
    python-version: python3
    requirements: snap-virtualenv-requirements.txt
    source: .
    stage-packages:
      - devscripts
      - apt
      - libnotify-bin
      - findutils
      - wget
    build-packages:
      - libapt-pkg-dev
