name: ubuntu-watch-packages
version: '0.4.2'
summary: Helpful utility to watch specified packages in the ubuntu archive.
description: |
  Watch specified packages in the
  ubuntu archive for transition between archive pockets. Useful when waiting
  for a package update to be published.

  It polls the launchpad API for new packages every 10 minutes (you can
  change this by using poll-seconds option)

  Usage:

  ubuntu-watch-packages --help # to see all available options

grade: stable
confinement: strict

apps:
  ubuntu-watch-packages:
    command: wrapper
    plugs:
      - network
      - desktop
      - home

parts:
  ubuntu-watch-packages-wrapper:
    plugin: dump
    source: snap/local
    prepare: |
      chmod +x wrapper
    stage:
      - usr/bin/wrapper
    organize:
      wrapper: usr/bin/wrapper

  ubuntu-watch-packages:
    plugin: python
    python-version: python3
    requirements: snap-virtualenv-requirements.txt
    source: .
    stage-packages:
      - devscripts
      - apt
      - libnotify-bin
      - python3-launchpadlib
      - distro-info
      - python3-distro-info
    build-packages:
      - libapt-pkg-dev
