name: ubuntu-watch-packages
version: '0.4.4'
base: core18
summary: Helpful utility to watch specified packages in the ubuntu archive.
description: |
  Watch specified binary packages in the
  ubuntu archive for transition between archive pockets. Useful when waiting
  for a package update to be published.

  It polls the launchpad API for new packages every 10 minutes (you can
  change this by using poll-seconds option)

  Usage:

  ubuntu-watch-packages --help # to see all available options

grade: stable
confinement: strict

apps:
  ubuntu-watch-packages:
    environment:
      PATH: "$SNAP/usr/bin:$SNAP/bin/:$PATH"
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
      JOBLIB_MULTIPROCESSING: 0
    command: usr/bin/python3 $SNAP/bin/ubuntu-watch-packages
    plugs:
      - network
      - desktop
      - home

parts:
  ubuntu-watch-packages:
    plugin: python
    requirements:
     - snap-virtualenv-requirements.txt
     - src/requirements.txt
    source: .
    stage-packages:
      - devscripts
      - apt
      - libnotify-bin
      - python3-launchpadlib
      - distro-info
      - python3-distro-info
    build-packages:
      - libapt-pkg-dev
