name: ubuntu-watch-packages
version: '0.1'
summary: Helpful utility to watch specified packages in the ubuntu archive.
description: |
  Watch specified packages, using the web service used by rmadison, in the
  ubuntu archive for transition between archive pockets. Useful when waiting
  for a package update to be published.

  It polls for new packages every 10 minutes (you can change this by using
  poll-seconds option)
grade: stable
confinement: strict

apps:
  ubuntu-watch-packages:
    command: wrapper
    plugs:
      - network
      - desktop
      - home

parts:
  ubuntu-watch-packages-wrapper:
    plugin: dump
    source: snap
    prepare: |
      chmod +x wrapper
    stage:
      - usr/bin/wrapper
    organize:
      wrapper: usr/bin/wrapper

  ubuntu-watch-packages:
    plugin: python
    python-version: python3
    requirements: snap-virtualenv-requirements.txt
    source: .
    stage-packages:
      - devscripts
      - apt
      - libnotify-bin
    build-packages:
      - libapt-pkg-dev
